[package]
name = "bank_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
actix-web = "2.0"
actix-rt = "1.0"
listenfd = "0.3"
serde = "1.0.145"
chrono = "0.4"
