[package]
name = "src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.1.0"
env_logger = "0.7.1"
serde_json = "1.0.51"

serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "1.4.0", features = ["time"] }